"""initial_schema

Revision ID: b8f626ee3f59
Revises: 
Create Date: 2026-08-22 10:16:54.721827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f626ee3f59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_logo', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_settings_id'), ['id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_position', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('residing_address', sa.Text(), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_job_position'), ['job_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_manager_id'), ['manager_id'], unique=False)

    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_allocation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_types_name'), ['name'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('work_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('extra_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', name='attendancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_employee_attendance_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_id'), ['id'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certifications_id'), ['id'], unique=False)

    op.create_table('employee_private_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('uan', sa.String(length=30), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_private_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_private_info_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_private_info_id'), ['id'], unique=False)

    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill')
    )
    with op.batch_alter_table('employee_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_skills_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.CheckConstraint('allocated_days >= 0', name='chk_leave_allocated_nonneg'),
    sa.CheckConstraint('remaining_days >= 0', name='chk_leave_remaining_nonneg'),
    sa.CheckConstraint('used_days >= 0', name='chk_leave_used_nonneg'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_emp_leave_type_year')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_leave_type_id'), ['leave_type_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_id'), ['id'], unique=False)

    op.create_table('salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('monthly_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yearly_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('standard_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performance_bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leave_travel_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employee_pf', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employer_pf', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('basic_salary >= 0', name='chk_salary_basic_salary_nonneg'),
    sa.CheckConstraint('employee_pf >= 0', name='chk_salary_epf_nonneg'),
    sa.CheckConstraint('employer_pf >= 0', name='chk_salary_emppf_nonneg'),
    sa.CheckConstraint('fixed_allowance >= 0', name='chk_salary_fixed_allowance_nonneg'),
    sa.CheckConstraint('hra >= 0', name='chk_salary_hra_nonneg'),
    sa.CheckConstraint('leave_travel_allowance >= 0', name='chk_salary_lta_nonneg'),
    sa.CheckConstraint('monthly_wage >= 0', name='chk_salary_monthly_wage_nonneg'),
    sa.CheckConstraint('performance_bonus >= 0', name='chk_salary_perf_bonus_nonneg'),
    sa.CheckConstraint('professional_tax >= 0', name='chk_salary_ptax_nonneg'),
    sa.CheckConstraint('standard_allowance >= 0', name='chk_salary_standard_allowance_nonneg'),
    sa.CheckConstraint('yearly_wage >= 0', name='chk_salary_yearly_wage_nonneg'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salaries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salaries_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HR_OFFICER', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_login_id'), ['login_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('time_off_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('number_of_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leaverequeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='chk_time_off_dates_valid'),
    sa.CheckConstraint('number_of_days > 0', name='chk_time_off_days_pos'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_leave_type_id'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_requests_status'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_leave_type_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_employee_id'))

    op.drop_table('time_off_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_login_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salaries_id'))
        batch_op.drop_index(batch_op.f('ix_salaries_employee_id'))

    op.drop_table('salaries')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_employee_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_leave_type_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('employee_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_employee_skills_employee_id'))

    op.drop_table('employee_skills')
    with op.batch_alter_table('employee_private_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_private_info_id'))
        batch_op.drop_index(batch_op.f('ix_employee_private_info_employee_id'))

    op.drop_table('employee_private_info')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_id'))
        batch_op.drop_index(batch_op.f('ix_certifications_employee_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_date'))

    op.drop_table('attendances')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_id'))

    op.drop_table('skills')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_types_name'))
        batch_op.drop_index(batch_op.f('ix_leave_types_id'))

    op.drop_table('leave_types')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_manager_id'))
        batch_op.drop_index(batch_op.f('ix_employees_job_position'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index(batch_op.f('ix_employees_department'))

    op.drop_table('employees')
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_settings_id'))

    op.drop_table('company_settings')
    # ### end Alembic commands ###
